apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v8
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: kubernetesonarm/etcd
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        command:
        - /usr/bin/etcd
        - -data-dir
        - /var/etcd/data
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
        volumeMounts:
        - name: etcd-storage
          mountPath: /var/etcd/data
      - name: kube2sky
        image: kubernetesonarm/kube2sky
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
#        command = "/kube2sky"
        - -domain=cluster.local
#        - -kube_master_url=KUBEMASTER
      - name: skydns
        image: kubernetesonarm/skydns
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/skydns"
        - -machines=http://localhost:4001
        - -addr=0.0.0.0:53
        - -domain=cluster.local
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 8080
#            scheme: HTTP
#          initialDelaySeconds: 30
#          timeoutSeconds: 5
      - name: healthz
        image: kubernetesonarm/exechealthz
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=/bin/sh -c "nslookup kubernetes.default.svc.cluster.local localhost >/dev/null"
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.